#!/usr/bin/env node
/*
 Simple integration smoke tests for JoinUp API.
 Usage:
   cd QA/backend
   npm install axios
   node api-tests.js

 The script expects the backend to be running at http://localhost:3000
 It will exercise auth, events, registrations, attendance, certificates and audit endpoints.
*/

const axios = require('axios');
const BASE = 'http://localhost:3000';

async function run() {
  try {
    console.log('--- 1) Login as admin ---');
    const adminLogin = await axios.post(`${BASE}/auth/login`, {
      email: 'admin@bootcamp.com',
      password: 'admin123'
    });
    const adminToken = adminLogin.data.accessToken;
    console.log('admin token length:', adminToken && adminToken.length);

    console.log('--- 2) Login as staff ---');
    const staffLogin = await axios.post(`${BASE}/auth/login`, {
      email: 'staff@bootcamp.com',
      password: 'staff123'
    });
    const staffToken = staffLogin.data.accessToken;

    console.log('--- 3) Login as participant ---');
    const partLogin = await axios.post(`${BASE}/auth/login`, {
      email: 'participant1@bootcamp.com',
      password: 'participant123'
    });
    const partToken = partLogin.data.accessToken;

    console.log('--- 4) List events (public) ---');
    const events = await axios.get(`${BASE}/events`);
    console.log('events count:', events.data.length);

    // Create an event as admin
    console.log('--- 5) Create a new event (admin) ---');
    const newEvent = await axios.post(`${BASE}/events`, {
      title: 'API Test Event',
      description: 'Generated by api-tests.js',
      startDate: new Date().toISOString(),
      endDate: new Date(Date.now() + 3600 * 1000).toISOString(),
      maxRegistrations: 10,
      categories: ['test'],
      price: 'free'
    }, { headers: { Authorization: `Bearer ${adminToken}` } });
    console.log('created event id:', newEvent.data.id || newEvent.data);
    const eventId = newEvent.data.id;

    // Register participant for event
    console.log('--- 6) Register participant for event ---');
    // Need a memberId for participant - list members as admin and pick participant
    const members = await axios.get(`${BASE}/auth/members`, { headers: { Authorization: `Bearer ${adminToken}` } });
    const participant = members.data.find(m => m.email === 'participant1@bootcamp.com') || members.data[0];
    const memberId = participant.id;
    const registration = await axios.post(`${BASE}/registrations/${eventId}/member/${memberId}`, null, { headers: { Authorization: `Bearer ${partToken}` } });
    console.log('registration id:', registration.data.id);
    const registrationId = registration.data.id;

    // Mark attendance as staff
    console.log('--- 7) Mark attendance (staff) ---');
    const attendance = await axios.post(`${BASE}/attendance/mark/${eventId}/member/${memberId}`, null, { headers: { Authorization: `Bearer ${staffToken}` } });
    console.log('attendance record id:', attendance.data.id || attendance.data);

    // Issue certificate as staff
    console.log('--- 8) Issue certificate (staff) ---');
    const cert = await axios.post(`${BASE}/certificates/issue/${registrationId}`, null, { headers: { Authorization: `Bearer ${staffToken}` } });
    console.log('certificate issued id:', cert.data.id);

    // Verify certificate
    console.log('--- 9) Verify certificate (using returned verificationCode) ---');
    const code = cert.data.verificationCode || cert.data.code || '1234';
    const verify = await axios.get(`${BASE}/certificates/verify/${registrationId}?code=${code}`);
    console.log('verify result:', verify.data);

    // Fetch audit as admin
    console.log('--- 10) Fetch audit logs (admin) ---');
    const audit = await axios.get(`${BASE}/audit?limit=10`, { headers: { Authorization: `Bearer ${adminToken}` } });
    console.log('audit entries:', (audit.data && audit.data.length) || audit.data);

    console.log('\nALL STEPS COMPLETED');
  } catch (err) {
    if (err.response) {
      console.error('HTTP Error:', err.response.status, err.response.data);
    } else {
      console.error('Error:', err.message);
    }
    process.exitCode = 1;
  }
}

run();
